version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker:
          docker_layer_caching: true

      # Install Hadolint
      - run:
          name: install-hadolint
          command: |
            wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x hadolint
            sudo mv hadolint /usr/local/bin/

      # Lint Dockerfile using Hadolint
      - run:
          name: lint-dockerfile
          command: hadolint Dockerfile

      # Run unit tests for backend
      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)

      # Build and push Docker image
      - run:
          name: build-app-karsajobs
          command: |
            chmod +x build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh
