apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service  # Nama service untuk aplikasi karsajobs-ui
spec:
  selector:
    app: karsajobs-ui  # Seleksi berdasarkan label app=karsajobs-ui
  ports:
    - protocol: TCP  # Protokol yang digunakan
      port: 80  # Port eksternal
      targetPort: 80  # Port internal pada pod yang dituju
  type: NodePort  # Tipe service yang digunakan
