apiVersion: apps/v1                           # Versi API yang digunakan untuk konfigurasi aplikasi Kubernetes
kind: Deployment                              # Jenis objek, yaitu Deployment
metadata:
  name: order-service                         # Nama deployment, dapat diganti sesuai kebutuhan
spec:
  replicas: 1                                 # Jumlah replika yang diinginkan, dalam hal ini 1
  selector:
    matchLabels:
      app: order-service                       # Label yang digunakan untuk memilih pod, dalam hal ini app: order-service
  template:
    metadata:
      labels:
        app: order-service                     # Label yang diberikan pada pod, dalam hal ini app: order-service
    spec:
      containers:
        - name: order-service                  # Nama kontainer, dalam hal ini order-service
          image: ghcr.io/popon0/a433-microservices/order-service:latest   # Image yang digunakan untuk kontainer
          ports:
            - containerPort: 3000               # Port yang digunakan dalam kontainer, dalam hal ini port 3000
          env:
            - name: AMQP_URL                    # Variabel lingkungan AMQP_URL
              value: amqp://reg:reg@10.108.186.167:5672   # Nilai variabel lingkungan AMQP_URL
