apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5673
      targetPort: 5672
    - protocol: TCP
      port: 15673
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/rabbitmq/
            - name: log-volume
              mountPath: /var/log/rabbitmq
      volumes:
        - name: data-volume
          hostPath:
            path: ~/.docker-conf/rabbitmq/data/
        - name: log-volume
          hostPath:
            path: ~/.docker-conf/rabbitmq/log/
