apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: ghcr.io/popon0/a433-microservices/shipping-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: AMQP_URL
              value: amqp://reg:reg@10.108.186.167:5672
