apiVersion: apps/v1                           # Versi API yang digunakan untuk konfigurasi aplikasi Kubernetes
kind: Deployment                              # Jenis objek, yaitu Deployment
metadata:
  name: shipping-service                       # Nama deployment, dapat diganti sesuai kebutuhan
spec:
  replicas: 1                                 # Jumlah replika yang diinginkan, dalam hal ini 1
  selector:
    matchLabels:
      app: shipping-service                    # Label yang digunakan untuk memilih pod, dalam hal ini app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service                  # Label yang diberikan pada pod, dalam hal ini app: shipping-service
    spec:
      containers:
        - name: shipping-service               # Nama kontainer, dalam hal ini shipping-service
          image: ghcr.io/popon0/a433-microservices/shipping-service:latest   # Image yang digunakan untuk kontainer
          ports:
            - containerPort: 3001               # Port yang digunakan dalam kontainer, dalam hal ini port 3001
          env:
            - name: AMQP_URL                    # Variabel env AMQP_URL
              value: amqp://reg:reg@10.108.186.167:5672   # Nilai variabel env AMQP_URL
